### ISSUE TITLE
Further modifications

### ISSUE THREAD

**Issue by Sarvam-Mittal** [datascience-playground/covid-19#3]
1) Have to extract the updated data and compare( will do once a week)
2) Once we think we have enough data than will work on model for forecasting or prediction
3) Have to learn about time series analysis
4) Have to create the final report (later)

**Comment by abhi18av** [comment]
@Sarvam-Mittal , again 'Further modifications` is not informative at all - try to summarise the question/request in one phrase. Otherwise people have to read the the description to gain a sense.

**Comment by abhi18av** [comment]
Here you could have created 4 different tasks.

**Comment by Sarvam-Mittal** [comment]
Okie will work on that .  And will create individual task from the next time
